envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DEVELOPMENT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
name: monkfish-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  - key: DJANGO_ALLOWED_HOST
    scope: RUN_AND_BUILD_TIME
    value: .ondigitalocean.app
  - key: DEVELOPMENT_MODE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  github:
    branch: main
    deploy_on_push: true
    repo: LogKul/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: pythonwebapps-02-profile-app
  routes:
  - path: /
  run_command: |-
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Project4-SuperheroProfiles/
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: LogKul/PythonWebApps
  name: pythonwebapps-02-profile-app-sta
  routes:
  - path: /static
  source_dir: Project4-SuperheroProfiles/static
