# Generated by Django 4.1 on 2022-10-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='created_by',
        ),
    ]
