# Generated by Django 4.1 on 2022-10-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_rename_author_article_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
