# Generated by Django 4.1 on 2022-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_article_options_superhero_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
