# Generated by Django 4.1 on 2022-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_alter_superhero_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(default='no_image.jpg', upload_to='images'),
        ),
    ]
