# Generated by Django 4.1 on 2022-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_alter_superhero_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='image',
        ),
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images'),
        ),
    ]
