# Generated by Django 4.1 on 2022-11-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_remove_superhero_image_alter_superhero_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
